// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjt4yWHt8NSZ3R_sHIrjkHbZpHAwrDAnA',
    appId: '1:1098415447936:web:7b7a147531b6bb6b13ab65',
    messagingSenderId: '1098415447936',
    projectId: 'plant-care-94574',
    authDomain: 'plant-care-94574.firebaseapp.com',
    storageBucket: 'plant-care-94574.firebasestorage.app',
    measurementId: 'G-M06R3Q6JJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HdDr24paRaU6c17szhpfr2NgouCG6h8',
    appId: '1:1098415447936:android:7428caaf0f000fa113ab65',
    messagingSenderId: '1098415447936',
    projectId: 'plant-care-94574',
    storageBucket: 'plant-care-94574.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3pvPEgQYN7JPgtyY1AZkNB2R4l5dBQSs',
    appId: '1:1098415447936:ios:63c699985c464ec413ab65',
    messagingSenderId: '1098415447936',
    projectId: 'plant-care-94574',
    storageBucket: 'plant-care-94574.firebasestorage.app',
    iosBundleId: 'com.example.plantCare',
  );
}
